[package]
name = "web3api-wasm-rs"
version = "0.1.0"
description = "Web3API Rust-WASM Runtime"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#bincode = "1.3.3"
failure = "0.1.8"
num = "0.4.0"
num-bigint = "0.4.0"
serde = { version = "1.0.126", features = ["derive"] }
wasm-bindgen = "0.2.63"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
