[package]
name = "polywrap-wasm-rs"
version = "0.1.0"
description = "Polywrap Rust-WASM Runtime"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num = "0.4.0"
num-bigint = "0.4.0"
serde = { version = "1.0.126", features = ["derive"] }
