[package]
name = "polywrap-wasm-rs"
version = "0.0.1-prealpha-dev.37.4"
license = "MIT"
description = "Polywrap's Rust-Wasm Runtime"
homepage = "https://polywrap.io"
documentation = "https://docs.polywrap.io"
repository = "https://github.com/polywrap/monorepo"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
keywords = ["polywrap", "wasm", "webassembly"]
categories = ["wasm"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num = "0.4.0"
num-bigint = "0.4.2"

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
# Tell `rustc` to optimize for small code size.
opt-level = "z"
debug = false
panic = "abort"