[package]
name = "query"
version = "0.1.0"
description = "Polywrap Query Test Cases"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num = "0.4.0"
num-bigint = "0.4.0"
polywrap-wasm-rs = "0.0.1-prealpha-dev.37.4"

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
# Tell `rustc` to optimize for small code size.
opt-level = "z"
debug = false
panic = "abort"
