format: 0.1.0
displayName: Meta manifest
tags:
  - test
  - meta
subtext: checks meta manifest works
description: test description
repository: https://github.com/test/test
invocations:
  - method: getInformation
  - method: setInformation
    arguments:
      firstArg: "foo"
      secondArg: 0