format: 0.0.1-prealpha.1
stages:
  ipfs_deploy:
    package: ipfs
    uri: fs/./build
  from_deploy:
    package: ens
    depends_on: ipfs_deploy
    config:
      domainName: test1.eth
      provider: 'foo'
      ensRegistryAddress: '0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab'
  from_deploy2:
    package: ens
    depends_on: ipfs_deploy
    config:
      domainName: test2.eth
      provider: 'http://localhost:8545'
      ensRegistryAddress: '0xe78A0F7E598Cc8b0Bb87894B0F60dD2a88d6a8Ab'