version: '3'
services:
  ganache:
    image: 'trufflesuite/ganache-cli:v6.12.2'
    ports:
      - '8545:8545'
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
  dev-server:
    build: ./
    ports:
      - '3000:3000'
    links:
      - ganache
    environment:
      ganache: 'ganache:8545'
      DEV_SERVER_PORT: '3000'
