[package]
name = "polywrap-rust-schema"
version = "0.1.0"
description = "Defining the generated code for the Polywrap Rust-WASM runtime"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "1.3.3"
num-bigint = { version = "0.4.0", features = ["serde"] }
num-traits = "0.2.14"
serde = { version = "1.0.126", features = ["derive"] }
wasm-bindgen = "0.2.63"
polywrap-wasm-rs = { version = "0.1.0", path = "../../../../../wasm/rs"}
polywrap-rust-test-cases = { version = "0.1.0", path = "../../../../../test-cases/cases/bind/sanity/output/wasm-rs" }