[package]
name = "polywrap-mutation"
version = "0.1.0"
description = "Polywrap Mutation Test Cases"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = "1.3.3"
num-bigint = { version = "0.4.0", features = ["serde"] }
num-traits = "0.2.14"
serde = { version = "1.0.126", features = ["derive"] }
polywrap-wasm-rs = { version = "0.1.0", path = "../../../../../wasm/rs" }
polywrap-query = { version = "0.1.0", path = "../query" }

[profile.release]
opt-level = "s"
