[package]
name = "mutation"
version = "0.1.0"
description = "Mutation module of rust-sanity example polywrapper"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[dependencies]
num-traits = { version = "0.2.14", default-features = false }
polywrap-wasm-rs = { version = "0.0.1-prealpha-dev.37.4", path = "../../../../../wasm/rs"}
query = { version = "0.1.0", path = "../query" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true          # turn on Link-Time Optimizations
codegen-units = 1   # trade compile time with maximum optimization
opt-level = "z"     # optimize for size
debug = false
debug-assertions = false
incremental = false
overflow-checks = true
panic = "abort"

[profile.dev]
panic = "abort"
