[package]
name = "mutation"
version = "0.1.0"
description = "Polywrap Mutation Test Cases"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num-bigint = { version = "0.4.2", features = ["serde"] }
num-traits = "0.2.14"
serde = { version = "1.0.126", features = ["derive"] }
polywrap-wasm-rs = { version = "0.0.1-prealpha-dev.37.4", path = "../../../../../wasm/rs"}
query = { version = "0.1.0", path = "../query" }

[profile.release]
lto = true
codegen-units = 1
overflow-checks = true
# Tell `rustc` to optimize for small code size.
opt-level = "s"
debug = false
