format: 0.0.1-prealpha.1
stages:
  ipfs_deploy:
    package: ipfs
    uri: fs/./build
  from_deploy:
    package: ens
    depends_on: ipfs_deploy
    config:
      domainName: simplestorage.eth
      provider: 'http://localhost:8545'
      ensRegistryAddress: '0x2c5f3c004878923f55A2a255F89Fe29393177509'
